name: publish_conda

on:
  release:
    types: [ published ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Conda environment creation and activation
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.8
          environment-file: conda/env.yaml
          auto-update-conda: false
          auto-activate-base: false
          show-channel-urls: true
      - name: Build and upload the conda packages
        uses: uibcdf/action-build-and-upload-conda-packages@v1.1-beta.1
        with:
          meta_yaml_dir: conda
          python-version: 3.8
          user: ace-internal
          label: auto
          token: ${{ secrets.ANACONDA_TOKEN }} # Replace with the right name of your secret
